replicaCount: 1
image:
  useImagePullSecrets: false
  pullPolicy: Always
service:
  internalPort: 3000
  externalPort: 80
ingress:
  enabled: false
  #basedomain: CHANGE_TO_YOUR_DNS.REGION.aksapp.io # replace with your own from the portal
